# Numpy练手教程

#### 基本数据类型——数组

In [7]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print (a.shape)
print(a[0],a[1],a[2])
print(a)
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[1 2 3]
(2, 3)
1 2 4


#### 生成数组

In [9]:
# 全零
a = np.zeros((2,2))
print(a)

# 全一
b = np.ones((2,3))
print(b)

#全为固定值
c = np.full((2,2),7)

#方阵
d= np.eye((2))
print(d)

#随机阵
e = np.random.random((2,2))
print(e)

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.40006049  0.27279295]
 [ 0.07642495  0.27934225]]


#### 数组下标

In [44]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[1,0])
print(a[0,:])
print(a[:,0])

5
[1 2 3 4]
[1 5 9]


#### 数据类型

In [24]:
x = np.array([1,2])
print(type(x))
print(x.dtype)

x = np.array([1.0,2.0])
print(x.dtype)

x = np.array([1,2],dtype = np.int64)
print(x.dtype)

<class 'numpy.ndarray'>
int32
float64
int64


#### 数学计算

In [27]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x+y)
print(np.add(x,y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [29]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [30]:
#对应位置相乘
print(x*y)
print(np.multiply(x,y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


In [33]:
##点乘
print(x.dot(y))
print(np.dot(x,y))

[[ 19.  22.]
 [ 43.  50.]]
[[ 19.  22.]
 [ 43.  50.]]


In [31]:
print(x/y)
print(np.divide(x,y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [32]:
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [34]:
## 对行和列求和
print(x)
#所有元素求和
print(np.sum(x))
#对列求和
print(np.sum(x,axis = 0))
#对行求和
print(np.sum(x,axis = 1))

[[ 1.  2.]
 [ 3.  4.]]
10.0
[ 4.  6.]
[ 3.  7.]


In [35]:
#转置操作
print(x)
print(x.T)

[[ 1.  2.]
 [ 3.  4.]]
[[ 1.  3.]
 [ 2.  4.]]


#### Broadcasting


In [39]:
a = np.array([0.0,10.0,20.0,30.0])
b = np.array([1.0,2.0,3.0])
print(a[:,np.newaxis]+b)


[[  1.   2.   3.]
 [ 11.  12.  13.]
 [ 21.  22.  23.]
 [ 31.  32.  33.]]
